const {chromium}=require('/Users/shurashipai/.npm/_npx/420ff84f11983ee5/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{
const browser=await chromium.launch({executablePath:'/Applications/Brave Browser.app/Contents/MacOS/Brave Browser',headless:true,args:['--disable-gpu']});
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('file:///Users/shurashipai/Projects/Tidy/tidy_design.html');await page.evaluate(()=>document.fonts.ready);
const inventory=await page.evaluate(()=>({screens:document.querySelectorAll('.frame-wrap').length,groups:document.querySelectorAll('.flow-group').length,dimensions:[...document.querySelectorAll('.screen')].every(e=>e.offsetWidth===393&&e.offsetHeight===852),images:[...document.images].filter(i=>i.complete&&!i.naturalWidth).map(i=>i.src)}));
console.log('INVENTORY',JSON.stringify(inventory));
if(!process.argv.includes('--behavior-only'))await page.screenshot({path:'.impeccable/review/desktop.png'});
await page.evaluate(()=>{document.getElementById('board').style.zoom=1;});
for(const id of (process.argv.includes('--behavior-only')?[]:['welcome','home','photo-selection','review','confirmation','settings','compression-result','vault','calendar'])){
await page.locator(`[data-screen="${id}"] .screen`).screenshot({path:`.impeccable/review/${id}.png`});}
await page.evaluate(()=>{Tidy.openPrototype('welcome');});
await page.locator('#resetPrototype').click();
await page.setViewportSize({width:393,height:1180});if(!process.argv.includes('--behavior-only'))await page.screenshot({path:'.impeccable/review/mobile.png'});
await page.evaluate(()=>{Tidy.state.permissions.photos='full';Tidy.state.permissions.contacts='allowed';Tidy.state.scanned=true;Tidy.navigate('similar');});
console.log('INITIAL',await page.evaluate(()=>Tidy.totals(Tidy.state)));
await page.locator('#live [data-action="select"]').first().click();
const before=await page.evaluate(()=>Tidy.totals(Tidy.state));
await page.evaluate(()=>{Tidy.handle('preview','similar-0');Tidy.handle('back','similar');});
if((await page.evaluate(()=>Tidy.totals(Tidy.state).count))!==before.count)throw Error('Preview lost selection');
await page.evaluate(()=>{Tidy.navigate('review');Tidy.handle('confirm');Tidy.handle('cancelConfirm');});
if((await page.evaluate(()=>Tidy.state.deleted.size))!==0)throw Error('Cancel deleted an item');
await page.evaluate(()=>{Tidy.handle('confirm');Tidy.handle('clean');});
await page.waitForFunction(()=>Tidy.state.current==='result');
console.log('CLEANUP',await page.evaluate(()=>({totals:Tidy.totals(Tidy.state),deleted:Tidy.state.deleted.size,result:Tidy.state.result.length,storage:Tidy.storage(Tidy.state)})));
await page.locator('#resetPrototype').click();
await page.evaluate(()=>{Tidy.handle('loadExample');});
assert.equal(await page.evaluate(()=>Tidy.totals(Tidy.state).count),83);
assert.ok(Math.abs(await page.evaluate(()=>Tidy.totals(Tidy.state).mb)-4800)<0.01);
await page.evaluate(()=>{Tidy.handle('edit','screenshots');Tidy.handle('select','screenshots-0');Tidy.navigate('review');});
assert.equal(await page.evaluate(()=>Tidy.totals(Tidy.state).count),82);
await page.evaluate(()=>{Tidy.handle('confirm');Tidy.handle('cancelConfirm');});
assert.equal(await page.evaluate(()=>Tidy.state.deleted.size),0);
await page.evaluate(()=>{Tidy.state.forcePartial=true;Tidy.handle('confirm');Tidy.handle('clean');});
await page.waitForFunction(()=>Tidy.state.current==='partial');
assert.equal(await page.evaluate(()=>Tidy.state.failed.length),2);
assert.equal(await page.evaluate(()=>Tidy.state.result.length),80);
assert.equal(await page.evaluate(()=>Tidy.state.selected.size),2);
await page.evaluate(()=>{Tidy.handle('retry');Tidy.handle('confirm');Tidy.handle('clean');});
await page.waitForFunction(()=>Tidy.state.current==='result');
assert.equal(await page.evaluate(()=>Tidy.state.deleted.size),82);
await page.evaluate(()=>Tidy.navigate('history'));
assert.ok((await page.locator('#live').innerText()).includes('2 cleanups'));
await page.locator('#resetPrototype').click();
await page.evaluate(()=>{Tidy.state.permissions.photos='limited';Tidy.state.permissions.contacts='denied';Tidy.navigate('similar');});
assert.ok((await page.locator('#live').innerText()).includes('8 photos'));
await page.evaluate(()=>Tidy.navigate('contacts'));
assert.equal(await page.evaluate(()=>Tidy.state.current),'contacts-denied');
await page.evaluate(()=>{Tidy.state.permissions.photos='denied';Tidy.navigate('home');});
assert.ok((await page.locator('#live').innerText()).includes('Manage Permissions'));
await page.evaluate(()=>{Tidy.state.permissions.photos='full';Tidy.state.permissions.calendar='allowed';Tidy.handle('select','similar-2');Tidy.handle('select','calendar-0');Tidy.navigate('calendar-review');Tidy.handle('go','calendar-confirm');Tidy.handle('clean');});
await page.waitForFunction(()=>Tidy.state.current==='result');
assert.deepEqual(await page.evaluate(()=>[...Tidy.state.deleted]),['calendar-0']);
assert.deepEqual(await page.evaluate(()=>[...Tidy.state.selected]),['similar-2']);
await page.evaluate(()=>{Tidy.navigate('compression');Tidy.handle('compress');});
await page.waitForFunction(()=>Tidy.state.current==='compression-result');
assert.equal(await page.evaluate(()=>Tidy.state.deleted.has('videos-0')),false);
assert.equal(await page.evaluate(()=>Tidy.state.compressedCopyMB),430);
await page.evaluate(()=>{Tidy.handle('go','remove-original');Tidy.handle('cancelConfirm');});
assert.equal(await page.evaluate(()=>Tidy.state.deleted.has('videos-0')),false);
await page.evaluate(()=>{Tidy.handle('go','remove-original');Tidy.handle('removeOriginalConfirm');});
assert.equal(await page.evaluate(()=>Tidy.state.deleted.has('videos-0')),true);
assert.ok(Math.abs((await page.evaluate(()=>Tidy.storage(Tidy.state).used))-93.43)<0.001);
await page.evaluate(()=>{Tidy.state.vault=[0,1];Tidy.handle('unlockVault');Tidy.handle('vaultSelect','0');Tidy.handle('removeVaultSelection');});
assert.deepEqual(await page.evaluate(()=>Tidy.state.vault),[1]);
assert.equal(await page.evaluate(()=>Tidy.state.deleted.has('similar-0')),false);
console.log('PASS: review consistency, preview/back, cancel, partial failure, retry, permissions, scoped calendar deletion, compression original safety, vault separation');
await page.evaluate(()=>{Tidy.state.preview='similar-5';Tidy.handle('nextPhoto');});
assert.equal(await page.evaluate(()=>Tidy.state.preview),'similar-0');
await page.evaluate(()=>{Tidy.state.eventsUsed=true;Tidy.navigate('system-settings');});
assert.equal(await page.locator('#live [data-value="calendar:allowed"]').count(),1);
await page.locator('#live [data-value="calendar:allowed"]').click();
assert.equal(await page.evaluate(()=>Tidy.state.permissions.calendar),'allowed');
console.log('PASS: group-only preview navigation and Calendar permission restoration');
console.log('ERRORS',errors);if(errors.length)throw Error(errors.join('\n'));
await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
